# Site settings
title: Ahmad A. Almazi
description: Ahmad A. Almazi - Portfolio

# User settings
username: Ahmad Almazi
user_description: I thrive to use data driven automation technology to create successful projects adapting innovation that fulfils the core needs of various markets.
user_title: Computer Science Engineer & Digital Marketer
email: mail@aalmazi.com
twitter_username: AlmaziAhmad
github_username:  almazi
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
